name: Deploy lambda to S3 for prod

on:
  workflow_dispatch:

jobs:
  deploy_lambda:
    strategy:
      matrix:
        include:
          - region: "us-east-2"
            bucket: "acorn-provisioning-cf-us-east-220230413224010722900000001"
          - region: "us-west-2"
            bucket: "acorn-provisioning-cf-us-west-220230413224011053200000001"
          - region: "eu-north-1"
            bucket: "acorn-provisioning-cf-eu-north-120230413224011490400000001"
    name: Build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: "1.20"
      - name: make package
        run: make package
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_PROD }}
          aws-region: ${{ matrix.region }}
      - name: Deploy new code to s3 bucket
        run: |
          aws s3 cp aws-registration-callback.zip s3://${{ matrix.bucket }}/aws-registration-callback.zip
