name: Deploy template to S3 for prod

on:
  workflow_dispatch:
  schedule:
    - cron: "00 16 * * 1-5" # time in UTC

jobs:
  auto_deploy_template:
    if: ${{ vars.ENABLED == 'true' && github.event_name != 'workflow_dispatch' }}
    strategy:
      matrix:
        include:
          - region: "us-east-2"
            bucket: "acorn-reg-us-east-2-prod20230730204111204100000001"
          - region: "us-west-2"
            bucket: "acorn-reg-us-west-2-prod20230730204111646800000001"
          - region: "eu-north-1"
            bucket: "acorn-reg-eu-north-1-prod20230730204112655900000001"
    name: Deploy template to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure AWS credentials from prod account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_PROD }}
          aws-region: ${{ matrix.region }}
      - name: Copy files to S3
        run: |
          latest=$(ls template | sort -V | tail -1)
          jq '.Parameters.Principal.Default = "${{ secrets.AWS_DEFAULT_PRINCIPAL }}" | .Resources.AcornSetAccountCredentialsLambda.Properties.Code.S3Bucket = "${{ matrix.bucket }}"' template/$latest > template/$latest.processed
          aws s3 cp template/$latest.processed s3://${{ matrix.bucket }}/$latest
  manual_deploy_template:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        include:
          - region: "us-east-2"
            bucket: "acorn-reg-us-east-2-prod20230730204111204100000001"
          - region: "us-west-2"
            bucket: "acorn-reg-us-west-2-prod20230730204111646800000001"
          - region: "eu-north-1"
            bucket: "acorn-reg-eu-north-1-prod20230730204112655900000001"
    name: Deploy template to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure AWS credentials from prod account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_PROD }}
          aws-region: ${{ matrix.region }}
      - name: Copy files to S3
        run: |
          latest=$(ls template | sort -V | tail -1)
          jq '.Parameters.Principal.Default = "${{ secrets.AWS_DEFAULT_PRINCIPAL }}" | .Resources.AcornSetAccountCredentialsLambda.Properties.Code.S3Bucket = "${{ matrix.bucket }}"' template/$latest > template/$latest.processed
          aws s3 cp template/$latest.processed s3://${{ matrix.bucket }}/$latest
