name: Update Dev Lambda

on:
  workflow_dispatch:
  push:
    ignore-paths:
      - 'template/**'
      - '.github/**'
    branches:
      - main

jobs:
  deploy_lambda:
    env:
      TAG: main
    name: Build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        env:
          REGISTRY: "${{ secrets.ECR_REGISTRY }}"
          TAG: ${{ env.TAG }}
        run: make image

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}:${{ env.TAG }}