name: Deploy template for dev

on:
  workflow_dispatch:
  push:
    paths:
      - 'template/**'
    branches:
      - main

jobs:
  deploy_template:
    env:
      TAG: main
    name: Deploy template to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Copy files to S3
        run: |
          latest=$(ls template | sort -V | tail -1)
          jq '.Parameters.Principal.Default = "${{ secrets.AWS_DEFAULT_PRINCIPAL }}" | .Resources.AcornSetAccountCredentialsLambda.Properties.Code.ImageUri = "${{ secrets.ECR_REGISTRY }}:${{ env.TAG }}"' template/$latest > template/$latest.processed
          aws s3 cp template/$latest.processed s3://${{ secrets.CF_TEMPLATE_BUCKET }}/$latest