name: Deploy template to S3 for main

on:
  workflow_dispatch:
  push:
    paths:
      - "template/**"
    branches:
      - main

jobs:
  deploy_template:
    strategy:
      matrix:
        include:
          - region: "us-east-2"
            bucket: "acorn-reg-us-east-2-main20230730204236706800000001"
          - region: "us-west-2"
            bucket: "acorn-reg-us-west-2-main20230730204237095400000001"
          - region: "eu-north-1"
            bucket: "acorn-reg-eu-north-1-main20230730204238938500000001"
    name: Deploy template to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure AWS credentials from main account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_MAIN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_MAIN }}
          aws-region: ${{ matrix.region }}
      - name: Copy files to S3
        run: |
          latest=$(ls template | sort -V | tail -1)
          jq '.Parameters.Principal.Default = "${{ secrets.AWS_DEFAULT_PRINCIPAL }}" | .Resources.AcornSetAccountCredentialsLambda.Properties.Code.S3Bucket = "${{ matrix.bucket }}"' template/$latest > template/$latest.processed
          aws s3 cp template/$latest.processed s3://${{ matrix.bucket }}/$latest
