name: deploy-lambda

on:
  workflow_dispatch:
  push:
    ignore-paths:
      - 'template/**'
    branches:
      - main

jobs:
  deploy_lambda:
    name: Build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: "1.20"
      - name: make package
        run: make package
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy new code to lambda
        run: |
          aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FN_ARN }} --zip-file fileb://aws-registration-callback.zip